//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEditor.UIElements;
using UnityEngine.UIElements;

namespace Endava.BuildAndDeploy.UxmlBindings
{
	public partial struct BuildStepsModuleBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly ListView buildStepList;
		public readonly VisualElement ctr_customfooter;
		public readonly Button removebutton;
		public readonly Button addbutton;

		public BuildStepsModuleBinding(VisualElement parent)
		{
			_____root_____ = parent;
			buildStepList = parent.Q<ListView>("buildStepList");
			ctr_customfooter = parent.Q<VisualElement>("ctr_custom-footer");
			removebutton = parent.Q<Button>("remove-button");
			addbutton = parent.Q<Button>("add-button");
		}
	}
}
