//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEditor.UIElements;
using UnityEngine.UIElements;

namespace Endava.BuildAndDeploy.UxmlBindings
{
	public partial struct BuildOverviewBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly Label headlineLabel;
		public readonly Label subtitleLabel;
		public readonly VisualElement ctrbuildprocesses;
		public readonly ToolbarSearchField searchfield;
		public readonly ToolbarButton refreshBtn;
		public readonly VisualElement refreshBtnIcon;
		public readonly ListView processList;
		public readonly VisualElement ctrempty;
		public readonly Label emptyLabel;

		public BuildOverviewBinding(VisualElement parent)
		{
			_____root_____ = parent;
			headlineLabel = parent.Q<Label>("headlineLabel");
			subtitleLabel = parent.Q<Label>("subtitleLabel");
			ctrbuildprocesses = parent.Q<VisualElement>("ctr-buildprocesses");
			searchfield = parent.Q<ToolbarSearchField>("searchfield");
			refreshBtn = parent.Q<ToolbarButton>("refreshBtn");
			refreshBtnIcon = parent.Q<VisualElement>("refreshBtnIcon");
			processList = parent.Q<ListView>("processList");
			ctrempty = parent.Q<VisualElement>("ctr-empty");
			emptyLabel = parent.Q<Label>("emptyLabel");
		}
	}
}
