//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEditor.UIElements;
using UnityEngine.UIElements;

namespace Endava.BuildAndDeploy.UxmlBindings
{
	public partial struct BuildOverviewListItemBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly VisualElement icon;
		public readonly Label name;
		public readonly Button BuildBtn;
		public readonly VisualElement stateIcon;
		public readonly Button GoToBtn;

		public BuildOverviewListItemBinding(VisualElement parent)
		{
			_____root_____ = parent;
			icon = parent.Q<VisualElement>("icon");
			name = parent.Q<Label>("name");
			BuildBtn = parent.Q<Button>("BuildBtn");
			stateIcon = parent.Q<VisualElement>("stateIcon");
			GoToBtn = parent.Q<Button>("GoToBtn");
		}
	}
}
