//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEditor.UIElements;
using UnityEngine.UIElements;

namespace Endava.BuildAndDeploy.UxmlBindings
{
	public partial struct ScenesModuleBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly VisualElement sceneListroot;
		public readonly Label headline;
		public readonly Button optionsBtn;
		public readonly Label optionsBtnLabel;
		public readonly ListView scenesList;

		public ScenesModuleBinding(VisualElement parent)
		{
			_____root_____ = parent;
			sceneListroot = parent.Q<VisualElement>("sceneList-root");
			headline = parent.Q<Label>("headline");
			optionsBtn = parent.Q<Button>("optionsBtn");
			optionsBtnLabel = parent.Q<Label>("optionsBtnLabel");
			scenesList = parent.Q<ListView>("scenesList");
		}
	}
}
