//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEditor.UIElements;
using UnityEngine.UIElements;

namespace Endava.BuildAndDeploy.UxmlBindings
{
	public partial struct ScenesModuleListItemBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly PropertyField sceneObjectField;

		public ScenesModuleListItemBinding(VisualElement parent)
		{
			_____root_____ = parent;
			sceneObjectField = parent.Q<PropertyField>("sceneObjectField");
		}
	}
}
