//<auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//</auto-generated>

using UnityEditor.UIElements;
using UnityEngine.UIElements;

namespace Endava.BuildAndDeploy.UxmlBindings
{
	public partial struct LoggingModuleBinding
	{
		private VisualElement _____root_____; // avoid name collisions!
		public VisualElement GetRootElement() => _____root_____;

		public readonly EnumField logLevelField;
		public readonly EnumFlagsField logTargetsField;
		public readonly Label logFileHint;

		public LoggingModuleBinding(VisualElement parent)
		{
			_____root_____ = parent;
			logLevelField = parent.Q<EnumField>("logLevelField");
			logTargetsField = parent.Q<EnumFlagsField>("logTargetsField");
			logFileHint = parent.Q<Label>("logFileHint");
		}
	}
}
